name: Scope

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run test
      run: docker run --rm $(docker build -q .)
      env:
        SCOPE_DSN: ${{secrets.SCOPE_DSN}} 
