name: Scope

on:
  push:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run test
      run: docker run -v /home/runner/work/containered-test/containered-test/logs:/var/log/scope -e SCOPE_DSN --rm $(docker build -q .)
      env:
        SCOPE_DSN: ${{secrets.SCOPE_DSN}}

    - uses: actions/upload-artifact@v1
      with:
        name: logs
        path: /home/runner/work/containered-test/containered-test/logs
